apiVersion: v1
kind: Service
metadata:
  labels:
    app: user2-cotd-dev
  name: user2-cotd-dev
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: user2-cotd-dev
  sessionAffinity: None
  type: ClusterIP
